version: '3'

services:
  ml-auth:
    build: .
    working_dir: /ngrana/ngrana
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/ngrana
    ports:
      - "8000:8000"
