#!/usr/bin/env bash

# run environment for testing nGrana exercises:

# test ML auth:
# =================

# create components
docker-compose build ml-auth

# run container
docker-compose up

# go to http://localhost:8000


# test todo list:
# =================

# create components
docker-compose build todo-list

# run container
docker-compose up

# go to http://localhost:3000
